# Defined in https://gitlab.com/dkml/base/containers/-/tree/main/src/avalonia-base
# Mirrored to https://github.com/diskuv/dkml-containers
# Releases:
#   https://gitlab.com/dkml/base/containers/container_registry/8730762
#   https://github.com/diskuv/dkml-containers/pkgs/container/avalonia-base
#
# The GitLab one should have anonymous access but for some reason it requires auth.
#FROM registry.gitlab.com/dkml/base/containers/avalonia-base:11.3.0.1
FROM ghcr.io/diskuv/avalonia-browser-base:11.3.0.4

# If you need anything else added to the container, try it out
# here. If it works send a PR to https://gitlab.com/dkml/base/containers.git
